### ISSUE TITLE
메인페이지, 마이페이지 Accordion 렌더링 수정 필요합니다.

### ISSUE THREAD

**Issue by MinwooPark93** [Book-ing/Book-ing_FE#1]
@Taak-e 

메인페이지, 마이페이지의 Accordion내부 데이터 렌더링의 수정이 필요합니다.

현재 배포된 내용은 study Type 을 따지지 않는데,
향후 webRTC 기능을 추가함에  따라 study Type에 따른 렌더링 차이가 있어야 합니다.

`studyType === "online"` 
스터디 타입에 따른 삼항연산자를 사용하여 null 과 현재 존재하는 태그를 나타내면 될 것 같습니다.

**Comment by Taak-e** [comment]
수정 사항 반영했습니다 감사합니다 :)
