### ISSUE TITLE
현재 스터디 참가/취소 리팩토링

### ISSUE THREAD

**Issue by ho-bolt** [Book-ing/Book-ing_FE#4]
현재 스터디 참가/취소 api를 리팩토링하여 스터디 시작시간이 지난 다음에는 참가 취소 버튼이 먹히지 않습니다!
이때 알럿을 띄어주시면 감사하겠습니다!
바쁘신데 추가되어서 죄송합니다 ㅜㅠ

**Comment by Taak-e** [comment]
리팩토링한 api 에 대한 수정사항 반영했습니다 감사합니다 :)
